### ISSUE TITLE
Issue creating the secure boot entry.

### ISSUE THREAD

**Issue by epic0421** [zeroxoneafour/arch-secureboot#1]
For some reason, whenever I run this command near the end of your script, I get this error:

`$ sudo efibootmgr --create --disk $(findmnt /efi -o SOURCE | grep "/dev") --loader /EFI/${bootloader_id}/shimx64.efi --label "$bootloader_id (Secure Boot)"`

`Could not prepare Boot variable: No such file or directory`

**Comment by epic0421** [comment]
My grub is located in `/boot/EFI/Arch/grubx64.efi` on an NVME SSD and that was the only file that I had in there before starting the install script. I also updated the secureboot.conf script from `esp="/efi"` to `esp="/boot"`

**Comment by epic0421** [comment]
I ended up figuring it out. The first /efi in the command I mentioned needed to be updated to /boot for me, and then it worked without a problem. Changing /efi to ${esp} or $esp fixed the issue entirely for me.

`$ sudo efibootmgr --create --disk $(findmnt ${esp} -o SOURCE | grep "/dev") --loader /EFI/${bootloader_id}/shimx64.efi --label "$bootloader_id (Secure Boot)"`

`$ sudo efibootmgr --create --disk $(findmnt $esp -o SOURCE | grep "/dev") --loader /EFI/${bootloader_id}/shimx64.efi --label "$bootloader_id (Secure Boot)"`

**Comment by zeroxoneafour** [comment]
Closed by #2 authored by issue opener

**Comment by zeroxoneafour** [comment]
Theres a few more things I want to commit from my branch to the upstream, Ill release a new version to the aur soon
