### ISSUE TITLE
"Boot entry already exists, not adding another" despite not having the secure boot entry in efibootmgr

### ISSUE THREAD

**Issue by epic0421** [zeroxoneafour/arch-secureboot#3]
After turning off secure boot and doing a fresh grub reinstallation, I tried to run your updated script and ran into this issue:

![2022-10-24_18 55 08](https://user-images.githubusercontent.com/85042398/197664479-46dac40d-9de7-4bac-b4de-b9a9c1b74210.png)

**Comment by zeroxoneafour** [comment]
I encountered this error too. It appears that the secureboot entry is deleted when it's not recreated. The previous version of the code actually duplicated the entries, so I don't really know why this is happening.

In the meantime, I'll revert that new feature addition. I guess it's better to have duplicate entries than a missing entry?

**Comment by epic0421** [comment]
> I encountered this error too. It appears that the secureboot entry is deleted when it's not recreated. The previous version of the code actually duplicated the entries, so I don't really know why this is happening.
> 
> In the meantime, I'll revert that new feature addition. I guess it's better to have duplicate entries than a missing entry?

Newest 0.2.3 version worked for me without any problems.

If you are trying to prevent duplicate secure boot entries, I ended up not getting any without that feature addition. I also think that having the Arch (Secure Boot) and Arch entries are fine since the Arch entry can be a fallback.

**Comment by zeroxoneafour** [comment]
I’m glad the newest update works well. Idk how it works really, but I guess I won’t touch it. The separate secure boot and normal boot entries is indeed intended behavior
